# The URL the site will be built for
base_url = "https://git.mendess.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

theme = "clean-blog"

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

title = "~mendess"

[extra]
# Put all your custom variables here
author = "mendess"
clean_blog_social = [
    {url = "https://github.com/mendess", icon="fab fa-github"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"},
]
clean_blog_menu = [
    {url = "$BASE_URL/projects", name = "Projects"},
    {url = "$BASE_URL/about", name = "About"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"
