name: Build

on:
    push:
        branches: [ dev ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  persist-credentials: false
            - name: Download Zola
              run: |
                curl https://api.github.com/repos/getzola/zola/releases/latest |
                    grep -o '"browser_download_url.*linux.*tar.gz"' |
                    cut -d : -f 2,3 |
                    tr -d \" |
                    wget -qi -
                gunzip zola*gz
                tar xf zola*tar
            - name: Build
              run: ./zola build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: master
                  FOLDER: public
